import { useEffect, useMemo, useState, type ReactNode } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { getConversations, updateConversation } from './api/conversations'
import type { Conversation, ConversationStatus } from './types/conversation'
import { useUIStore, type Filter } from './store/ui-store'

const filters: { label: string; value: Filter }[] = [{ label: 'Urgent', value: 'urgent' }, { label: 'Low CSAT', value: 'low-csat' }, { label: 'Waiting longest', value: 'waiting' }, { label: 'Unassigned', value: 'unassigned' }]
const avatars = ['bg-[#e9d9ff] text-[#7051a6]', 'bg-[#ccefe9] text-[#267c73]', 'bg-[#ffe1ce] text-[#b66133]', 'bg-[#dbe6ff] text-[#4161ab]', 'bg-[#fce4e8] text-[#b35565]', 'bg-[#e2e7ec] text-[#586b7e]']
const statusText: Record<ConversationStatus, string> = { new: 'New', assigned: 'Assigned', snoozed: 'Snoozed', resolved: 'Resolved' }
const sentiment: Record<Conversation['sentiment'], { label: string; className: string }> = { negative: { label: 'Negative', className: 'text-[#cf4f63]' }, neutral: { label: 'Neutral', className: 'text-[#a97922]' }, positive: { label: 'Positive', className: 'text-[#298c76]' } }

type IconProps = { size?: number; className?: string }
function Glyph({ size = 16, className }: IconProps) { return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className={className} aria-hidden="true"><path d="M4 12h16M12 4v16" /><circle cx="12" cy="12" r="8" /></svg> }
const Archive = Glyph, ArrowUpRight = Glyph, AtSign = Glyph, Bot = Glyph, Check = Glyph, ChevronDown = Glyph, CircleAlert = Glyph, Clock3 = Glyph, Ellipsis = Glyph, InboxIcon = Glyph, Lightning = Glyph, LockKeyhole = Glyph, MessageSquareText = Glyph, MoreHorizontal = Glyph, Paperclip = Glyph, Search = Glyph, Send = Glyph, Sparkles = Glyph, UserPlus = Glyph

function Avatar({ conversation, small = false }: { conversation: Conversation; small?: boolean }) {
  const c = avatars[Number(conversation.id.replace(/\D/g, '')) % avatars.length]
  return <div className={`flex shrink-0 items-center justify-center rounded-full font-bold ${c} ${small ? 'h-7 w-7 text-[10px]' : 'h-10 w-10 text-xs'}`}>{conversation.customer.initials}</div>
}

function IconButton({ children, label, onClick }: { children: ReactNode; label: string; onClick?: () => void }) {
  return <button type="button" onClick={onClick} aria-label={label} className="flex h-8 w-8 items-center justify-center rounded-lg text-[#6e7785] transition hover:bg-[#f1f3f6] hover:text-[#242b38]">{children}</button>
}

function ConversationCard({ item, active, onSelect }: { item: Conversation; active: boolean; onSelect: () => void }) {
  const mood = sentiment[item.sentiment]
  return <button type="button" onClick={onSelect} className={`relative w-full border-b border-[#edf0f2] px-4 py-3 text-left transition hover:bg-[#f8fafb] ${active ? 'bg-[#eef7f7] hover:bg-[#eef7f7]' : 'bg-white'}`}>
    {active && <span className="absolute inset-y-0 left-0 w-[3px] bg-[#16837c]" />}
    <div className="flex gap-2.5"><Avatar conversation={item} small /><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><p className="truncate text-[13px] font-semibold text-[#202938]">{item.customer.name}</p><span className={`mt-0.5 h-5 min-w-5 rounded-full px-1.5 text-center text-[10px] font-bold leading-5 ${item.priorityScore >= 90 ? 'bg-[#f9dce3] text-[#cc3f58]' : item.priorityScore >= 70 ? 'bg-[#fff0c5] text-[#a86b0e]' : 'bg-[#eaf0f2] text-[#637180]'}`}>{item.priorityScore}</span></div><p className="mt-0.5 truncate text-[12px] leading-4 text-[#657080]">{item.reason}</p><div className="mt-2 flex items-center justify-between"><span className={`flex items-center gap-1 text-[10px] font-medium ${mood.className}`}><i className="h-1.5 w-1.5 rounded-full bg-current" />{mood.label}</span><span className="text-[10px] font-medium text-[#8a94a2]">{item.waitingMinutes >= 60 ? `${Math.floor(item.waitingMinutes / 60)}h ${item.waitingMinutes % 60}m` : `${item.waitingMinutes}m`}</span></div></div></div>
  </button>
}

function Inbox({ conversations }: { conversations: Conversation[] }) {
  const { selectedId, setSelected, filter, setFilter, search, setSearch } = useUIStore()
  const filtered = useMemo(() => conversations.filter((item) => {
    const match = `${item.customer.name} ${item.reason} ${item.customer.company}`.toLowerCase().includes(search.toLowerCase())
    const matchFilter = filter === 'all' || (filter === 'urgent' && item.priority === 'urgent') || (filter === 'low-csat' && item.sentiment === 'negative') || (filter === 'waiting' && item.waitingMinutes >= 60) || (filter === 'unassigned' && !item.assignee && item.status === 'new')
    return match && matchFilter
  }).sort((a, b) => b.priorityScore - a.priorityScore), [conversations, filter, search])
  useEffect(() => { if (!selectedId && filtered[0]) setSelected(filtered[0].id) }, [filtered, selectedId, setSelected])
  return <aside className="hidden h-full w-full shrink-0 flex-col border-r border-[#e5e8eb] bg-white md:flex md:w-[340px] lg:w-[30%] lg:min-w-[330px]">
    <div className="border-b border-[#e8ebee] px-4 pb-3 pt-4"><div className="mb-4 flex items-center justify-between"><div className="flex items-center gap-2"><div className="flex h-8 w-8 items-center justify-center rounded-[10px] bg-[#1a8d86] text-white"><InboxIcon size={16} /></div><div><h1 className="text-[15px] font-bold tracking-[-.02em] text-[#1e2937]">Inbox</h1><p className="text-[10px] text-[#85909d]">Priority conversations</p></div></div><IconButton label="Inbox menu"><MoreHorizontal size={18} /></IconButton></div><label className="relative block"><Search size={15} className="pointer-events-none absolute left-3 top-2.5 text-[#929ba7]" /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search conversations" className="h-9 w-full rounded-lg border border-[#e0e5e8] bg-[#fafbfc] pl-9 pr-3 text-xs text-[#2a3340] outline-none placeholder:text-[#9ba4af] focus:border-[#55a8a1] focus:ring-2 focus:ring-[#d9f0ed]" /></label><div className="mt-3 flex gap-1.5 overflow-x-auto pb-0.5">{filters.map((chip) => <button type="button" key={chip.value} onClick={() => setFilter(filter === chip.value ? 'all' : chip.value)} className={`whitespace-nowrap rounded-full border px-2.5 py-1 text-[10px] font-semibold transition ${filter === chip.value ? 'border-[#1b8a83] bg-[#e0f3f0] text-[#13766f]' : 'border-[#e0e5e7] bg-white text-[#667383] hover:border-[#a9cfc9]'}`}>{chip.label}</button>)}</div></div>
    <div className="flex items-center justify-between border-b border-[#edf0f2] px-4 py-2.5"><p className="text-[11px] font-semibold text-[#677382]">All conversations <span className="ml-1 rounded bg-[#eef1f3] px-1.5 py-0.5 text-[10px]">{filtered.length}</span></p><button className="text-[10px] font-semibold text-[#16837c]">Newest <ChevronDown size={11} className="ml-0.5 inline" /></button></div>
    <div className="min-h-0 flex-1 overflow-y-auto">{filtered.length ? filtered.map((item) => <ConversationCard key={item.id} item={item} active={item.id === selectedId} onSelect={() => setSelected(item.id)} />) : <div className="px-8 py-20 text-center"><Archive className="mx-auto text-[#a4adb7]" size={28} /><p className="mt-3 text-sm font-semibold text-[#334050]">No conversations found</p><p className="mt-1 text-xs text-[#7d8895]">Try clearing a filter or search.</p></div>}</div>
  </aside>
}

function BriefCard({ conversation }: { conversation: Conversation }) {
  return <section className="group rounded-xl border border-[#e5e9eb] bg-white p-4 shadow-[0_2px_8px_rgba(37,50,62,.04)] transition hover:-translate-y-0.5 hover:shadow-[0_8px_20px_rgba(37,50,62,.09)]"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><span className="flex h-6 w-6 items-center justify-center rounded-lg bg-[#e4f4f1] text-[#16837c]"><Sparkles size={13} /></span><h3 className="text-xs font-bold text-[#263140]">AI Brief</h3></div><span className="rounded-full bg-[#eff8f6] px-2 py-0.5 text-[9px] font-bold text-[#16837c]">Updated now</span></div><p className="mt-3 text-[11px] leading-[1.55] text-[#5f6c7b]">{conversation.summary}</p><button className="mt-3 text-[10px] font-semibold text-[#16837c]">View full timeline <ArrowUpRight size={11} className="inline" /></button></section>
}

function Signals({ conversation }: { conversation: Conversation }) {
  const risk = conversation.priorityScore >= 90 ? 'High' : conversation.priorityScore >= 70 ? 'Elevated' : 'Normal'
  return <section className="group rounded-xl border border-[#e5e9eb] bg-white p-4 shadow-[0_2px_8px_rgba(37,50,62,.04)] transition hover:-translate-y-0.5 hover:shadow-[0_8px_20px_rgba(37,50,62,.09)]"><div className="flex items-center gap-2"><span className="flex h-6 w-6 items-center justify-center rounded-lg bg-[#f0edff] text-[#7562c8]"><Lightning size={13} /></span><h3 className="text-xs font-bold text-[#263140]">Signals</h3></div><div className="mt-3 space-y-2.5"><div className="flex items-center justify-between"><span className="text-[10px] text-[#718091]">Priority score</span><span className="rounded-md bg-[#fce8ec] px-1.5 py-0.5 text-[10px] font-bold text-[#c73d55]">{conversation.priorityScore}/100</span></div><div className="flex items-center justify-between"><span className="text-[10px] text-[#718091]">Churn risk</span><span className="flex items-center gap-1 text-[10px] font-bold text-[#c76c36]"><i className="h-1.5 w-1.5 rounded-full bg-[#e89048]" />{risk}</span></div><div className="flex items-center justify-between"><span className="text-[10px] text-[#718091]">Customer sentiment</span><span className={`text-[10px] font-bold ${sentiment[conversation.sentiment].className}`}>{sentiment[conversation.sentiment].label}</span></div><div className="border-t border-[#eef0f2] pt-2.5"><div className="mb-1.5 flex justify-between text-[10px] text-[#718091]"><span>Response SLA</span><span className="font-semibold text-[#d06c38]">{conversation.waitingMinutes}m waiting</span></div><div className="h-1.5 overflow-hidden rounded-full bg-[#edf0f2]"><div className="h-full rounded-full bg-[#e89150]" style={{ width: `${Math.min(96, Math.max(22, conversation.waitingMinutes / 2))}%` }} /></div></div></div></section>
}

function ConversationPanel({ conversation, onAction, pending }: { conversation?: Conversation; onAction: (update: Partial<Conversation>) => void; pending: boolean }) {
  const [draft, setDraft] = useState('')
  if (!conversation) return <main className="flex flex-1 items-center justify-center bg-[#f8fafb]"><div className="text-center"><MessageSquareText className="mx-auto text-[#b6bec8]" size={32} /><p className="mt-3 text-sm font-semibold text-[#34404d]">Choose a conversation</p></div></main>
  const isEscalated = conversation.priorityScore >= 70
  return <main className="relative flex min-w-0 flex-1 flex-col bg-white"><header className="z-10 flex h-[73px] shrink-0 items-center justify-between border-b border-[#e7ebed] px-5"><div className="flex min-w-0 items-center gap-3"><Avatar conversation={conversation} /><div className="min-w-0"><div className="flex items-center gap-2"><h2 className="truncate text-[15px] font-bold text-[#202a37]">{conversation.customer.name}</h2>{isEscalated && <span className="flex items-center gap-1 rounded-full bg-[#fcedef] px-1.5 py-0.5 text-[9px] font-bold text-[#c84058]"><CircleAlert size={10} /> Escalated</span>}</div><p className="mt-0.5 text-[11px] text-[#778392]">{conversation.customer.company} <span className="px-1 text-[#c0c6cd]">•</span> Customer since 2022</p></div></div><div className="hidden items-center gap-1 sm:flex"><IconButton label="Search in conversation"><Search size={16} /></IconButton><IconButton label="More actions"><Ellipsis size={18} /></IconButton></div></header>
    <div className="min-h-0 flex-1 overflow-y-auto bg-[#fbfcfd] px-5 py-5"><div className="mx-auto max-w-[660px]"><div className="mb-5 flex items-center gap-3"><div className="h-px flex-1 bg-[#e7eaed]" /><span className="text-[10px] font-medium text-[#9aa4ae]">Today</span><div className="h-px flex-1 bg-[#e7eaed]" /></div><div className="space-y-5"><div className="flex items-start gap-2.5"><Avatar conversation={conversation} small /><div className="max-w-[82%]"><div className="mb-1 flex items-baseline gap-2"><span className="text-[11px] font-bold text-[#344052]">{conversation.customer.name}</span><span className="text-[10px] text-[#9aa4ad]">10:14 AM</span></div><div className="rounded-[4px_14px_14px_14px] border border-[#e5e9ec] bg-white px-3.5 py-2.5 text-[12px] leading-[1.55] text-[#425061]">Hi team, {conversation.history[0]?.body.replace(/^I'm disappointed — /, '')}</div></div></div><div className="ml-9 border-l-2 border-[#d5e9e6] pl-3"><div className="mb-1 flex items-center gap-1.5"><span className="flex h-4 w-4 items-center justify-center rounded bg-[#ddf1ee] text-[#16837c]"><Bot size={10} /></span><span className="text-[10px] font-bold text-[#16837c]">Fin AI</span><span className="text-[10px] text-[#9aa4ad]">10:15 AM</span></div><p className="text-[11px] leading-[1.55] text-[#657283]">I understand this is frustrating. I’ve identified the issue and routed this to our specialist team.</p></div><div className="flex justify-end"><div className="max-w-[78%]"><div className="mb-1 flex items-baseline justify-end gap-2"><span className="text-[10px] text-[#9aa4ad]">10:18 AM</span><span className="text-[11px] font-bold text-[#344052]">You</span></div><div className="rounded-[14px_4px_14px_14px] bg-[#1d8e87] px-3.5 py-2.5 text-[12px] leading-[1.55] text-white">I’m looking into this for you now. I’ll update you shortly with the next steps.</div></div></div></div></div></div>
    <div className="shrink-0 border-t border-[#e7ebed] bg-white px-4 pb-3 pt-3"><div className="mx-auto max-w-[660px]"><div className="rounded-xl border border-[#dfe4e7] bg-white shadow-[0_2px_7px_rgba(40,50,60,.04)]"><textarea value={draft} onChange={(e) => setDraft(e.target.value)} placeholder={`Reply to ${conversation.customer.name}...`} className="h-[54px] w-full resize-none rounded-xl px-3 pt-3 text-[12px] text-[#3c4958] outline-none placeholder:text-[#a4adb7]" /><div className="flex items-center justify-between border-t border-[#f0f1f2] px-2 py-1.5"><div className="flex items-center gap-0.5"><IconButton label="Attach a file"><Paperclip size={15} /></IconButton><IconButton label="Add emoji"><span className="text-base">☺</span></IconButton><IconButton label="Mention someone"><AtSign size={15} /></IconButton></div><button type="button" onClick={() => setDraft('')} disabled={!draft.trim()} className="flex h-7 items-center gap-1 rounded-md bg-[#16837c] px-2.5 text-[10px] font-bold text-white transition hover:bg-[#11726c] disabled:opacity-40">Send <Send size={11} /></button></div></div></div></div>
    <div className="absolute bottom-3 left-5 z-20 hidden gap-2 xl:flex"><button disabled={pending || conversation.status === 'assigned'} onClick={() => onAction({ status: 'assigned', assignee: 'You' })} className="flex items-center gap-1.5 rounded-lg border border-[#dde4e5] bg-white px-2.5 py-1.5 text-[10px] font-semibold text-[#52606d] shadow-sm transition hover:border-[#86bdb7] hover:text-[#147b74] disabled:opacity-40"><UserPlus size={12} /> Assign</button><button disabled={pending} onClick={() => onAction({ status: 'snoozed' })} className="flex items-center gap-1.5 rounded-lg border border-[#dde4e5] bg-white px-2.5 py-1.5 text-[10px] font-semibold text-[#52606d] shadow-sm transition hover:border-[#86bdb7] hover:text-[#147b74]"><Clock3 size={12} /> Snooze</button><button disabled={pending || conversation.status === 'resolved'} onClick={() => onAction({ status: 'resolved' })} className="flex items-center gap-1.5 rounded-lg border border-[#dde4e5] bg-white px-2.5 py-1.5 text-[10px] font-semibold text-[#52606d] shadow-sm transition hover:border-[#86bdb7] hover:text-[#147b74]"><Check size={12} /> Resolve</button></div>
  </main>
}

function RightSidebar({ conversation, onAction }: { conversation?: Conversation; onAction: (update: Partial<Conversation>) => void }) {
  if (!conversation) return null
  return <aside className="hidden h-full w-[25%] min-w-[270px] flex-col overflow-y-auto border-l border-[#e5e8eb] bg-[#f8fafb] p-4 xl:flex"><BriefCard conversation={conversation} /><section className="group mt-3 rounded-xl border border-[#cde5e1] bg-[#f2faf9] p-4 shadow-[0_2px_8px_rgba(37,50,62,.03)] transition hover:-translate-y-0.5 hover:shadow-[0_8px_20px_rgba(37,50,62,.08)]"><div className="flex items-center gap-2"><span className="flex h-6 w-6 items-center justify-center rounded-lg bg-[#d8f0ec] text-[#16837c]"><Bot size={13} /></span><h3 className="text-xs font-bold text-[#263140]">Recommended next action</h3></div><p className="mt-3 text-[11px] font-semibold leading-[1.55] text-[#344a4a]">{conversation.nextAction}</p><button onClick={() => onAction({ status: 'assigned', assignee: 'You' })} className="mt-3 flex items-center gap-1 rounded-md bg-[#16837c] px-2.5 py-1.5 text-[10px] font-bold text-white transition hover:bg-[#11736d]">Take action <ArrowUpRight size={11} /></button></section><div className="mt-3"><Signals conversation={conversation} /></div><section className="mt-3 rounded-xl border border-[#e5e9eb] bg-white p-4"><h3 className="text-xs font-bold text-[#263140]">Customer details</h3><div className="mt-3 space-y-2.5 text-[10px]"><div className="flex justify-between"><span className="text-[#84909d]">Plan</span><span className="font-semibold text-[#475465]">Enterprise</span></div><div className="flex justify-between"><span className="text-[#84909d]">Owner</span><span className="font-semibold text-[#475465]">Unassigned</span></div><div className="flex justify-between"><span className="text-[#84909d]">Tags</span><span className="flex gap-1"><i className="rounded bg-[#eef1f3] px-1.5 py-0.5 not-italic text-[#647180]">billing</i><i className="rounded bg-[#eef1f3] px-1.5 py-0.5 not-italic text-[#647180]">vip</i></span></div></div></section></aside>
}

function Loading() { return <div className="flex h-screen bg-white"><div className="w-[30%] min-w-[330px] border-r border-[#e8ebee] p-4"><div className="h-8 w-28 animate-pulse rounded bg-[#edf0f2]" /><div className="mt-5 h-9 animate-pulse rounded-lg bg-[#f1f3f4]" />{Array.from({ length: 6 }).map((_, i) => <div className="mt-4 flex gap-3" key={i}><div className="h-8 w-8 animate-pulse rounded-full bg-[#eef1f3]" /><div className="flex-1 space-y-2"><div className="h-3 w-2/5 animate-pulse rounded bg-[#eef1f3]" /><div className="h-3 animate-pulse rounded bg-[#f4f5f6]" /></div></div>)}</div><div className="flex-1 p-8"><div className="h-10 w-48 animate-pulse rounded bg-[#eef1f3]" /><div className="mx-auto mt-16 max-w-lg space-y-5">{Array.from({ length: 4 }).map((_, i) => <div className={`h-16 animate-pulse rounded-xl bg-[#f2f4f5] ${i % 2 ? 'ml-auto w-3/5' : 'w-4/5'}`} key={i} />)}</div></div></div> }

export function App() {
  const client = useQueryClient(); const { selectedId, setSelected, setToast, toast } = useUIStore(); const query = useQuery({ queryKey: ['conversations'], queryFn: getConversations });
  const mutation = useMutation({ mutationFn: ({ id, update }: { id: string; update: Partial<Conversation> }) => updateConversation(id, update), onSuccess: (updated) => { client.setQueryData<Conversation[]>(['conversations'], (items = []) => items.map((item) => item.id === updated.id ? updated : item)); setToast('Conversation updated'); setTimeout(() => setToast(null), 2600) } });
  const selected = query.data?.find((item) => item.id === selectedId)
  useEffect(() => { const keydown = (event: KeyboardEvent) => { if (['INPUT', 'TEXTAREA'].includes((event.target as HTMLElement)?.tagName)) return; if (event.key === 'a' && selected) mutation.mutate({ id: selected.id, update: { status: 'assigned', assignee: 'You' } }); if (event.key === 'r' && selected) mutation.mutate({ id: selected.id, update: { status: 'resolved' } }) }; window.addEventListener('keydown', keydown); return () => window.removeEventListener('keydown', keydown) }, [mutation, selected])
  if (query.isLoading) return <Loading />
  if (query.isError) return <div className="flex min-h-screen items-center justify-center bg-[#f8fafb] p-6"><div className="rounded-xl border border-[#e4e7e9] bg-white p-7 text-center shadow-panel"><LockKeyhole className="mx-auto text-[#c45a69]" /><h1 className="mt-3 font-bold text-[#2c3744]">Inbox unavailable</h1><p className="mt-1 text-sm text-[#788391]">{query.error.message}</p><button onClick={() => query.refetch()} className="mt-4 rounded-lg bg-[#16837c] px-4 py-2 text-sm font-semibold text-white">Try again</button></div></div>
  const action = (update: Partial<Conversation>) => selected && mutation.mutate({ id: selected.id, update })
  return <div className="flex h-screen overflow-hidden bg-white"><Inbox conversations={query.data ?? []} /><ConversationPanel conversation={selected} pending={mutation.isPending} onAction={action} /><RightSidebar conversation={selected} onAction={action} />{toast && <div role="status" className="fixed bottom-5 right-5 z-50 rounded-lg bg-[#263641] px-3.5 py-2.5 text-xs font-semibold text-white shadow-xl">{toast}</div>}</div>
}
